### For presidential party votes with a larger margin of victory are there more independent votes?

In [2]:
import pandas as pd

In [16]:
pres = pd.read_csv("data/president_county_candidate.csv")

state_total = pd.read_csv("data/president_state.csv")

county = pd.read_csv("data/president_state.csv")

In [4]:
display(pres)

display(state_total)

          state             county      candidate party  total_votes    won
0      Delaware        Kent County      Joe Biden   DEM        44552   True
1      Delaware        Kent County   Donald Trump   REP        41009  False
2      Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3      Delaware        Kent County  Howie Hawkins   GRN          420  False
4      Delaware  New Castle County      Joe Biden   DEM       195034   True
...         ...                ...            ...   ...          ...    ...
32172   Arizona    Maricopa County      Write-ins   WRI         1331  False
32173   Arizona      Mohave County   Donald Trump   REP        78535   True
32174   Arizona      Mohave County      Joe Biden   DEM        24831  False
32175   Arizona      Mohave County   Jo Jorgensen   LIB         1302  False
32176   Arizona      Mohave County      Write-ins   WRI           37  False

[32177 rows x 6 columns]

                   state  total_votes
0               Delaware       504010
1   District of Columbia       344356
2                Florida     11067456
3                Georgia      4997716
4                 Hawaii       574469
5                  Idaho       868106
6               Illinois      6038843
7                Indiana      3033198
8                   Iowa      1690871
9                 Kansas      1375304
10              Kentucky      2136768
11             Louisiana      2148062
12                 Maine       819461
13              Maryland      3037030
14         Massachusetts      3631402
15              Michigan      5539302
16             Minnesota      3277171
17           Mississippi      1315182
18              Missouri      3025962
19               Montana       605750
20              Nebraska       956379
21                Nevada      1405376
22         New Hampshire       804430
23            New Jersey      4564234
24            New Mexico       923965
25              New York      8613546
26        North Carolina      5524801
27          North Dakota       361819
28                  Ohio      5922202
29              Oklahoma      1560699
30                Oregon      2374321
31          Pennsylvania      6925255
32          Rhode Island       517757
33        South Carolina      2513329
34          South Dakota       422609
35             Tennessee      3054534
36                 Texas     11317911
37                  Utah      1488289
38               Vermont       367428
39              Virginia      4460524
40            Washington      4087631
41         West Virginia       794652
42             Wisconsin      3297352
43               Wyoming       276765
44               Alabama      2323304
45                Alaska       359530
46              Arkansas      1219069
47            California     17495906
48              Colorado      3256953
49           Connecticut      1824280
50         United States    158432595
51               Arizona      3387326

In [5]:
new_list = pres[["state", "party", "total_votes"]]

new_pres = pd.merge(left = new_list, right = state_total, how = "left", on = "state")

display(new_pres)

          state party  total_votes_x  total_votes_y
0      Delaware   DEM          44552         504010
1      Delaware   REP          41009         504010
2      Delaware   LIB           1044         504010
3      Delaware   GRN            420         504010
4      Delaware   DEM         195034         504010
...         ...   ...            ...            ...
32172   Arizona   WRI           1331        3387326
32173   Arizona   REP          78535        3387326
32174   Arizona   DEM          24831        3387326
32175   Arizona   LIB           1302        3387326
32176   Arizona   WRI             37        3387326

[32177 rows x 4 columns]

In [9]:
bob = new_pres.groupby( ["state", "party"] ).agg(state_vote = ('total_votes_x', 'sum'))
bob = bob.reset_index()
print(bob)

       state party  state_vote
0    Alabama   DEM      849648
1    Alabama   LIB       25176
2    Alabama   REP     1441168
3    Alabama   WRI        7312
4     Alaska   ALI         318
..       ...   ...         ...
326  Wyoming   DEM       73491
327  Wyoming   IND        2208
328  Wyoming   LIB        5768
329  Wyoming   REP      193559
330  Wyoming   WRI        1739

[331 rows x 3 columns]

In [7]:
bob2 = pd.merge(left = bob, right = state_total, how = "left", on = "state")

bob2

       state party  state_vote  total_votes
0    Alabama   DEM      849648      2323304
1    Alabama   LIB       25176      2323304
2    Alabama   REP     1441168      2323304
3    Alabama   WRI        7312      2323304
4     Alaska   ALI         318       359530
..       ...   ...         ...          ...
326  Wyoming   DEM       73491       276765
327  Wyoming   IND        2208       276765
328  Wyoming   LIB        5768       276765
329  Wyoming   REP      193559       276765
330  Wyoming   WRI        1739       276765

[331 rows x 4 columns]

In [10]:
bob2["percentage"] = bob2["state_vote"] / bob2["total_votes"] * 100

display(bob2)

       state party  state_vote  total_votes  percentage
0    Alabama   DEM      849648      2323304   36.570677
1    Alabama   LIB       25176      2323304    1.083629
2    Alabama   REP     1441168      2323304   62.030970
3    Alabama   WRI        7312      2323304    0.314724
4     Alaska   ALI         318       359530    0.088449
..       ...   ...         ...          ...         ...
326  Wyoming   DEM       73491       276765   26.553574
327  Wyoming   IND        2208       276765    0.797789
328  Wyoming   LIB        5768       276765    2.084079
329  Wyoming   REP      193559       276765   69.936227
330  Wyoming   WRI        1739       276765    0.628331

[331 rows x 5 columns]

In [13]:
find_ind = bob2.loc[bob2["party"] == "IND"]

find_ind

                    state party  state_vote  total_votes  percentage
8                  Alaska   IND         825       359530    0.229466
21               Arkansas   IND        7715      1219069    0.632860
41               Colorado   IND       10672      3256953    0.327668
63   District of Columbia   IND         693       344356    0.201245
83                 Hawaii   IND        1183       574469    0.205929
89                  Idaho   IND        6440       868106    0.741845
108                  Iowa   IND        3754      1690871    0.222016
118              Kentucky   IND       10082      2136768    0.471834
125             Louisiana   IND        8397      2148062    0.390911
159             Minnesota   IND       13591      3277171    0.414717
169           Mississippi   IND        4316      1315182    0.328168
214              New York   IND       22650      8613546    0.262958
234              Oklahoma   IND       11798      1560699    0.755943
266             Tennessee   IND       10281      3054534    0.336582
280                  Utah   IND        9836      1488289    0.660893
297               Vermont   IND        2467       367428    0.671424
327               Wyoming   IND        2208       276765    0.797789